config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :links
  resources :blurbs
  resources :stores
  resources :services
  resources :sessions, only: [:new, :create, :destroy]
  
  root 'static_pages#home'
  match '/signup',    to: 'users#new',              via: 'get'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/locations', to: 'static_pages#locations', via: 'get'
  match '/admin',     to: 'static_pages#admin',     via: 'get'
  post 'send' =>          'static_pages#sendit'
  

end

app/models/blurb.rb
class Blurb
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :description, :type => String
  field :title,       :type => String
  
  validates :title,         presence: true
  validates :description,   presence: true
end

app/models/link.rb
class Link
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :url,    :type => String
  field :name,    :type => String
  
  validates :name, presence: true
  validates :url,  presence: true
end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :body

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :body

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/service.rb
class Service
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :desc,    :type => String
  field :name,    :type => String
  
  validates :name, presence: true
  validates :desc, presence: true
end

app/models/store.rb
class Store
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :address,   :type => String
  field :hours,     :type => String
  field :number,    :type => String
  field :title,     :type => String
  
  validates :title,   presence: true
  validates :hours,   presence: true
  validates :number,  presence: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :assets

  def assets
    @stores = Store.all
    @blurbs = Blurb.all
    @services = Service.all
    @links = Link.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  #before_action :admin_user, only: [:admin]

  def home
    @blurbs = Blurb.all
  end

  def about
  end

  def contact
    @links = Link.all
  end

  def admin
  end

  def locations
    @stores = Store.all
  end

  def index
    params[:email] ||= 'barnespeter213@gmail.com'
  end

  def sendit
    if UserMailer.email(params).deliver
      flash[:success] = "Your message has been sent"
    else
      flash[:error] = "Something went wrong"
    end
      redirect_to contact_path
  end

  private 
end

app/helpers/application_helper 2.rb
module ApplicationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blurbs_helper.rb
module BlurbsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar img-thumbnail")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.infinitetoken.com" target="blank">Infinite Token&reg;</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" 
              class="navbar-toggle" 
              data-toggle="collapse"
              data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Gameroom", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <!--Left navbar section-->
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#"
             class="dropdown-toggle"
             data-toggle="dropdown">
             Locations <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% @stores.each do |s| %>
              <li><a href="locations#<%= s.title %>"><%= s.title %></a></li>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#"
             class="dropdown-toggle"
             data-toggle="dropdown">
             Services <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% @services.each do |sv| %>
              <li><a href="services#<%= sv.name %>"><%= sv.name %></a></li>
            <% end %>
          </ul>
        </li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "About",   about_path   %></li>
      </ul>
      <!--Right navbar section-->
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gameroom for President</title>
  <meta charset="utf-8">
  <meta name="apple-mobile-web-app-capable" content = "yes">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Gameroom">
  <meta name="author" content="Gameroom">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet" type="text/css">
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"  type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel="stylesheet" type="text/css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul class="alert alert-danger">
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<div class="col-md-5 col-md-offset-1">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg %> 
      </div>
    <% end %>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="head"><i class="fa fa-users"></i> About us</h1>
  </div>
</div>
<div class="row about">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><i class="fa fa-user"></i> Who</h3>
      </div>
      <div class="panel-body">
        <p>
          Integer legentibus erat a ante historiarum dapibus. Hi omnes lingua, institutis, legibus inter se differunt. Mercedem aut nummos unde unde extricat, amaras. Quisque placerat facilisis egestas cillum dolore. Me non paenitet nullum festiviorem excogitasse ad hoc.
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><i class="fa fa-gamepad"></i> What</h3>
      </div>
      <div class="panel-body">
        <p>
          Fictum,  deserunt mollit anim laborum astutumque! Idque Caesaris facere voluntate liceret: sese habere. Tu quoque, Brute, fili mi, nihil timor populi, nihil! Tityre, tu patulae recubans sub tegmine fagi  dolor. Vivamus sagittis lacus vel augue laoreet rutrum faucibus.
Quid securi etiam tamquam eu fugiat nulla pariatur. Morbi odio eros, volutpat ut pharetra vitae, lobortis sed nibh. Integer legentibus erat a ante historiarum dapibus. Cum sociis natoque penatibus et magnis dis parturient.
Fabio vel iudice vincam, sunt in culpa qui officia. Mercedem aut nummos unde unde extricat, amaras. Cras mattis iudicium purus sit amet fermentum. Fictum,  deserunt mollit anim laborum astutumque!
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><i class="fa fa-building-o"></i> Where</h3>
      </div>
      <div class="panel-body">
        <p>Put address here</p>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><i class="fa fa-clock-o"></i> When</h3>
      </div>
      <div class="panel-body">
        <p>Hours here</p>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><i class="fa fa-question"></i> Why</h3>
      </div>
      <div class="panel-body">
        <p>
          Etiam habebis sem dicantur magna mollis euismod. Quid securi etiam tamquam eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident culpa. Quid securi etiam tamquam eu fugiat nulla pariatur. Inmensae subtilitatis, obscuris et malesuada fames.
Quam temere in vitiis, legem sancimus haerentia. Ambitioni dedisse scripsisse iudicaretur. Quam diu etiam furor iste tuus nos eludet? A communi observantia non est recedendum. Ab illo tempore, ab est sed immemorabili.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/admin.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>
          Blurbs <small>Appears on the home page</small>
          <%= link_to new_blurb_path, class: "pull-right btn btn-primary" do %>
            <i class="fa fa-plus"></i>
             New Blurb
          <% end %>
        </h2>
      </div>
      <div class="panel-body">
        <% @blurbs.each do |b| %>
          <h4 class="well"><i class="fa fa-<%= b.icon %>"></i> <%= b.title %>
            <%= link_to b, method: :delete, data: { confirm: "You sure?" } do %>
              <i class="fa fa-times-circle pull-right red"></i>
            <% end %>
            <%= link_to edit_blurb_path(b) do %>
              <i class="fa fa-pencil-square-o pull-right"></i>
            <% end %>
            <%= link_to b do %>
              <i class="fa fa-eye pull-right"></i>
            <% end %>                                                                     
          </h4>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>
          Stores <small>Appears on the locations page</small>
          <%= link_to new_store_path, class: "pull-right btn btn-primary" do %>
            <i class="fa fa-plus"></i>
            New Store
          <% end %>
        </h2>
      </div>
      <div class="panel-body">
        <% @stores.each do |s| %>
          <h4 class="well"><i class="fa fa-building-o"></i> <%= s.title %>  
            <%= link_to s, method: :delete, data: { confirm: "You sure?" } do %>
              <i class="fa fa-times-circle pull-right red"></i>
            <% end %>
            <%= link_to edit_store_path(s) do %>
              <i class="fa fa-pencil-square-o pull-right"></i>
            <% end %>
            <%= link_to s do %>
              <i class="fa fa-eye pull-right"></i>
            <% end %>
          </h4>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>
          Services <small>Appears on the services page</small>
          <%= link_to new_service_path, class: "pull-right btn btn-primary" do %>
            <i class="fa fa-plus"></i>
            New Service
          <% end %>
        </h2>
      </div>
      <div class="panel-body">
        <% @services.each do |sv| %>
          <h4 class="well"><i class="fa fa-<%= sv.icon %>"></i> <%= sv.name %>  
            <%= link_to sv, method: :delete, data: { confirm: "You sure?" } do %>
              <i class="fa fa-times-circle pull-right red"></i>
            <% end %>
            <%= link_to edit_service_path(sv) do %>
              <i class="fa fa-pencil-square-o pull-right"></i>
            <% end %>
            <%= link_to sv do %>
              <i class="fa fa-eye pull-right"></i>
            <% end %>
          </h4>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>
          Links <small>Appears on contact page</small>
          <%= link_to new_link_path, class: "pull-right btn btn-primary" do %>
            <i class="fa fa-plus"></i>
            New link
          <% end %>
        </h2>
      </div>
      <div class="panel-body">
        <% @links.each do |l| %>
          <h4 class="well"><i class="fa fa-<%= l.icon %>"></i> <%= l.name %>
            <%= link_to l, method: :delete, data: { confirm: "You sure?" } do %>
              <i class="fa fa-times-circle pull-right red"></i>
            <% end %>
            <%= link_to edit_link_path(l) do %>
              <i class="fa fa-pencil-square-o pull-right"></i>
            <% end %>
            <%= link_to l do %>
              <i class="fa fa-eye pull-right"></i>
            <% end %>
          </h4>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><i class="fa fa-users"></i> Follow us</h3>
      </div>
      <div class="panel-body">
        <% @links.each do |l| %>
          <a href="<%= l.url %>" 
             target="blank" 
             class="btn btn-primary btn-block">
             <i class="fa fa-<%= l.icon %>"></i>
             <%= l.name %>
           </a>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><i class="fa fa-comments"></i> Questions, comments, or concerns?</h3>
      </div>
      <div class="panel-body">
        <div class="emailform">
          <%= form_tag("/send", method: "post") do %>
            <div class="row">
              <div class="col-md-6 form-group">
                <%= label_tag(:name, "Name") %>
                <%= text_field_tag(:name, params[:name], class: "form-control") %>
                <hr noshade>
                <%= label_tag(:email, "Email") %>
                <%= text_field_tag(:email, params[:email], class: "form-control") %>
              </div>
              <div class="col-md-6 form-group">
                <%= label_tag(:body, "Message") %>
                <%= text_area_tag(:body, params[:body], class: "form-control", rows: "6") %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-1">
                <button type="submit" 
                        class="btn btn-primary">
                     <i class="fa fa-envelope-o"></i> 
                    Send
                </button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-md-12">
    <div>
      <%= image_tag("logo.png", :alt => "Logo", class: "center-block img-responsive") %>
    </div>
  </div>
</div>
<div class="row">
  <%= render @blurbs %>
</div>

app/views/static_pages/locations.html.erb
<div class="row">
  <div class="col-md-2 panel panel-default navlinks">
    <% @stores.each do |l| %>
      <h5><a href="#<%= l.title %>"><%= l.title %></a></h5>
    <% end %>
    <hr noshade>
    <h5><a href="#">Back to top</a></h5>
  </div>
</div>
<div class="row">
  <%= render @stores %>
</div>

app/views/static_pages/services.html.erb
<div class="row">
  <div class="col-md-2 panel panel-default navlinks">
    <h5><a href="#sell">Selling/Trading</a></h5>
    <h5><a href="#repair">Repairs</a></h5>
    <h5><a href="#disc">Disc cleaning</a></h5>
    <h5><a href="#volun">Volunteering</a></h5>
    <hr noshade>
    <h5><a href="#">Back to top</a></h5>
  </div>
</div>
<div class="row">
  <div class="col-md-9 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 id="sell" class="head"><i class="fa fa-money"></i> Selling/Trading</h4>
      </div>
      <div class="panel-body">
        <p>
          Quid securi etiam tamquam eu fugiat nulla pariatur. Vivamus sagittis lacus vel augue laoreet rutrum faucibus. Cum sociis natoque penatibus et magnis dis parturient. Cum ceteris in veneratione tui montes, nascetur mus.
Sed haec quis possit intrepidus aestimare tellus. Non equidem invideo, miror magis posuere velit aliquet. Plura mihi bona sunt, inclinet, amari petere vellent. Ab illo tempore, ab est sed immemorabili. Quid securi etiam tamquam eu fugiat nulla pariatur. Donec sed odio operae, eu vulputate felis rhoncus.
Ambitioni dedisse scripsisse iudicaretur. Non equidem invideo, miror magis posuere velit aliquet. Etiam habebis sem dicantur magna mollis euismod. Donec sed odio operae, eu vulputate felis rhoncus. Quid securi etiam tamquam eu fugiat nulla pariatur.
Integer legentibus erat a ante historiarum dapibus. Donec sed odio operae, eu vulputate felis rhoncus. Quisque placerat facilisis egestas cillum dolore. Prima luce, cum quibus mons aliud  consensu ab eo. Pellentesque habitant morbi tristique senectus et netus. Curabitur blandit tempus ardua ridiculus sed magna.
        </p>
      </div>
    </div>
  </div>
</div>